/**
 * Trades: Daily view / trade detail (satisfaction, tags, notes, excursions).
 */
export {
    satisfactionArray,
    satisfactionTradeArray,
    tradeIndex,
    tradeIndexPrevious,
    itemTradeIndex,
    excursion,
    excursions,
    notes,
    tags,
    tradeTags,
    newTradeTags,
    availableTags,
    availableTagsArray,
    tagInput,
    showTagsList,
    tradeNote,
    tradeNoteChanged,
    tradeNoteDateUnix,
    tradeNoteId,
    tradeTagsChanged,
    tradeTagsDateUnix,
    tradeTagsId,
    tradeExcursionChanged,
    tradeExcursionDateUnix,
    tradeExcursionId,
    tradeScreenshotChanged,
    auswertungNotes,
} from '../globals.js'
